### ISSUE TITLE
Error: Win NPM - cannot be loaded because running scripts is disabled on this system

### ISSUE THREAD

**Issue by JakubAndrysek** [cubicap/Jaculus-tools#1]
The system has disabled the running script and your system can’t accept the jac commands.

To enable that run this command in PowerShell
```
set-ExecutionPolicy RemoteSigned -Scope CurrentUser 
```

More [info](https://www.c-sharpcorner.com/article/how-to-fix-ps1-can-not-be-loaded-because-running-scripts-is-disabled-on-this-sys/)

**Comment by cubicap** [comment]
Because PowerShell does not allow execution of scripts by default, it has to be explicitly allowed using `Set-ExecutionPolicy`.

There are other possible workarounds which allow running the `jac` command without changing the execution policy:

- run the command in cmd instead of PowerShell - either directly or from PowerShell using `cmd /c jac [args]`
- run the command using npx - `npx jac [args]`

npx also does not require the script to be in the PATH but the startup is significantly slower than running the command directly in Powershell or cmd.
